{% set name = "signxml" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02065da169f33c519d7a9c7a60d96c9e0a245ee1015945f58e36f406899d8d13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - certifi >=2018.1.18
    - cryptography >=2.1.4, <4
    - eight >=0.4.2, <2
    - lxml >=4.2.1, <5
    - pyopenssl >=17.5.0, <21
    - python >=3.6

test:
  imports:
    - signxml
    - signxml.util

about:
  home: https://github.com/kislyuk/signxml
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python XML Signature library
  doc_url: https://signxml.readthedocs.io/en/latest/
  dev_url: https://github.com/kislyuk/signxml

extra:
  recipe-maintainers:
    - fhoehle
