{% set name = "signxml" %}
{% set version = "4.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e783299f85206538d7115ffdc8cb704f48d1ed3e066378f783d5fc251e24a5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - certifi >=2023.11.17
    - cryptography >=43
    - lxml >=5.2.1,<6
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - signxml
    - signxml.util

about:
  home: https://xml-security.github.io/signxml/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python XML Signature library
  doc_url: https://xml-security.github.io/signxml/
  dev_url: https://github.com/XML-Security/signxml

extra:
  recipe-maintainers:
    - fhoehle
