{% set name = "signxml" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65563053488073aa38681eb6ec49607b931c73f18dff1dbe38f59c772696e6b0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - certifi >=2023.11.17
    - cryptography >=43
    - lxml >=5.2.1, <6
    - python >=3.7

test:
  imports:
    - signxml
    - signxml.util

about:
  home: https://xml-security.github.io/signxml/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python XML Signature library
  doc_url: https://xml-security.github.io/signxml/
  dev_url: https://github.com/XML-Security/signxml

extra:
  recipe-maintainers:
    - fhoehle
