{% set name = "signxml" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 113264176bfe5597b8e3ebf01d37e06f02827b284952e956e7f22efa02f66634

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - certifi >=2023.11.17
    - cryptography >=43
    - lxml >=5.2.1, <6
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - signxml
    - signxml.util

about:
  home: https://xml-security.github.io/signxml/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python XML Signature library
  doc_url: https://xml-security.github.io/signxml/
  dev_url: https://github.com/XML-Security/signxml

extra:
  recipe-maintainers:
    - fhoehle
