schema_version: 1

context:
  name: signxml
  version: "4.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 038781783520e5d7bae4aa9c1e35f24fe9062730459da72009ce55126b56fa0f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vvv --no-deps

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - certifi >=2023.11.17
    - cryptography >=43
    - lxml >=5.2.1,<7
    - python >=${{ python_min }}
tests:
  - python:
      imports:
        - signxml
        - signxml.util
      python_version: ${{ python_min }}.*
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Python XML Signature library
  homepage: https://xml-security.github.io/signxml/
  repository: https://github.com/XML-Security/signxml
  documentation: https://xml-security.github.io/signxml/

extra:
  recipe-maintainers:
    - fhoehle
